const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const envDir = path.join(projectRoot, 'src', 'environments');
const envPath = path.join(envDir, 'environment.ts');

function loadDotEnvFile(fileName) {
  const filePath = path.join(projectRoot, fileName);

  if (!fs.existsSync(filePath)) {
    return;
  }

  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#') || !trimmed.includes('=')) {
      continue;
    }

    const [key, ...valueParts] = trimmed.split('=');
    const value = valueParts.join('=').trim().replace(/^["']|["']$/g, '');

    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

loadDotEnvFile('.env.local');
loadDotEnvFile('.env');

const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:5000/api';
const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY || '';
const production = process.env.NODE_ENV === 'production';

fs.mkdirSync(envDir, { recursive: true });

const fileContents = `// This file is generated by scripts/generate-env.cjs.
// Do not place real secrets in source control.
export const environment = {
  production: ${production},
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
  googleMapsApiKey: ${JSON.stringify(googleMapsApiKey)}
};
`;

fs.writeFileSync(envPath, fileContents);

console.log(`Generated ${path.relative(projectRoot, envPath)}`);

if (!process.env.GOOGLE_MAPS_API_KEY) {
  console.warn('GOOGLE_MAPS_API_KEY is not set. Google Maps will not load until a key is provided.');
}
